config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'top#index'
  resources :users, only: [:edit, :update, :show]
  resources :events, only: [:index, :new, :create, :edit, :update, :show] do
    resources :event_users, only: [:new, :create]
  end
  
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代以上' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :levelev

  with_options presence: true do
    validates :title,length: { maximum: 25, message: 'は25文字以内で入力してください' }
    validates :day
    validates :start_time
    validates :end_time
    validates :place
    validates :number,numericality: { only_integer: true }
    validates :cost,numericality: { only_integer: true }
    validates :text
  end

  validates :levelev_id, numericality: { other_than: 1, message: 'を選択してください'  }

end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event

end

app/models/level.rb
class Level < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '初級' },
    { id: 3, name: '初中級' },
    { id: 4, name: '中級' },
    { id: 5, name: '中上級' },
    { id: 6, name: '上級' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/levelev.rb
class Levelev < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '初級' },
    { id: 3, name: '初中級' },
    { id: 4, name: '中級' },
    { id: 5, name: '中上級' },
    { id: 6, name: '上級' },
    { id: 7, name: 'どなたでも' },
  ]

  include ActiveHash::Associations
  has_many :events
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '女性' },
    { id: 3, name: '男性' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角の英字と数字の両方を含めて設定してください' 
  
  validates :nickname, presence: true
  validates :image, presence: true

  with_options numericality: { other_than: 1, message: 'を選択してください'  } do
    validates :age_id
    validates :sex_id
    validates :level_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :age
    belongs_to_active_hash :sex
    belongs_to_active_hash :level

  has_many :event_users
  has_many :events
  has_one_attached :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :email, :password, :nickname, :age_id, :sex_id, :level_id, :history, :profile])
  end

end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController

  def new
    @event_user = EventUser.new
  end

  def create
    event_user = EventUser.new(event_user_params)
    if event_user.save
      redirect_to root_path
    else
      render event_path
    end
  end

  def show
    
  end

  private
  def event_user_params
    params.require(:event_user).permit(:text).merge(user_id: current_user.id, event_id: params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!,except: [:index, :show ]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @event_user = EventUser.new
    @events = @event.event_users
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

private

  def event_params
    params.require(:event).permit(:title, :day, :start_time, :end_time, :place, :place_url, :levelev_id, :limit, :number, :cost, :text, user_id: current_user.id ).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @event_users = @user.event_users
  end

  def edit 
  end
  
  def update 
    if current_user.update(user_params) 
      redirect_to root_path
    else
    render :edit
    end 
  end

  private
  def user_params 
    params.require(:user).permit(:image, :email, :nickname, :age_id, :sex_id, :level_id, :history, :profile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<div class="success">
<h3> イベントを作成しました！</h3>
<%= link_to "イ ベ ン ト 一 覧 に 戻 る  ＞", new_user_registration_url , class:"return" %>
</div>

app/views/events/index.html.erb
<div class='event-index'>

  <div class='event-main'>
    <%= image_tag "index_01.jpg", class:'event-main-image' %>
  </div>
    <%= image_tag "index_icon.svg", class:'event-title-icon' %>


  <ul class='event-lists-item'>
    <li class='status-item'>状況</li>
    <li class='date-time-item'>日程</li>
    <li class='event-contents-item'>内容</li>
    <li class='organizer-item'>主催者</li>
  </ul>

  <div class='event-lists'>
    <% @events.each do |event| %>
      <ul class='event-list'>
        <div class='status-box'>
          <li class='status'>募集中</li>
        </div>

        <li class='date-time'>
          <span class='date'>
          <%= event.day.year %>年<br>
          <%= event.day.month %>月
          <%= event.day.day %>日
          <% day = event.day.wday %>
          <% days = ["(日)", "(月)", "(火)", "(水)", "(木)", "(金)", "(土)"] %>
            <% if days[day] == "(日)"%>
              <span class='mon'><%= days[day] %></span>
            <% elsif days[day] == "(土)"%>
              <span class='sat'><%= days[day] %></span>
            <% else %>
              <%= days[day] %>
            <% end %>
        </span>
        </li>
      
        <li class='event-contents'>
          <% if event.levelev[:name] == "初級"%>
            <div class='level-2'><%= event.levelev[:name] %></div><% end %>
          <% if event.levelev[:name] == "初中級"%>
            <div class='level-3'><%= event.levelev[:name] %></div><% end %>
          <% if event.levelev[:name] == "中級"%>
            <div class='level-4'><%= event.levelev[:name] %></div><% end %>
          <% if event.levelev[:name] == "中上級"%>
            <div class='level-5'><%= event.levelev[:name] %></div><% end %>
          <% if event.levelev[:name] == "上級"%>
            <div class='level-6'><%= event.levelev[:name] %></div><% end %>
          <% if event.levelev[:name] == "どなたでも"%>
            <div class='level-7'><%= event.levelev[:name] %></div><% end %>
          <%= link_to event_path(event.id),class:"contents-title" do %>
            <%= event.title %>
          <% end %>
        </li>

        <li class='organizer'>
        <div class='user-img'>
          <%= link_to image_tag(event.user.image, class: "user-img"), "/users/#{event.user.id}" %></div>
          <%= link_to event.user.nickname, "/users/#{event.user.id}", class:'user-name'%>
        </li>

      </ul>
    <% end %>
  </div>

</div>

app/views/events/new.html.erb
<div class='event'>

<div class='title'>
  <h1 class='title-text'>
    イ ベ ン ト 内 容
  </h1>
</div>

<%= form_with(model: @event, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="field">
    <%= f.label "イベント名", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.text_field :title, class:"input-n" %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label "開催日", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
   <%= f.date_field :day,class:"input-day" %>
    </div>
  </div>

  <div class="field">
    <%= f.label "開催時間", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.time_select :start_time,{prompt:'--'}, {class:"input-time"} %>
       <span>〜</span>
    <%= f.time_select :end_time,{prompt:'--'}, {class:"input-time"} %>
    </div>
  </div>

  <div class="field">
    <%= f.label "会場", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.text_field :place, class:"input-n" %>
    </div>
  </div>

  <div class="field">
    <%= f.label "会場のURL", class:"item" %>
    <div class="any">任意</div>
    <div class="input">
    <%= f.text_field :place_url, class:"input-n" %>
    </div>
  </div>

  <div class="field">
    <%= f.label "参加レベル", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.collection_select(:levelev_id, Levelev.all, :id, :name, {}, class:"input-hash")%>
    </div>
  </div>

  <div class="field">
    <%= f.label "その他制限", class:"item" %>
    <div class="any">任意</div>
    <div class="input">
    <%= f.text_field :limit, class:"input-n", placeholder:"例）男性限定  20代限定" %>
    </div>
  </div>

  <div class="field">
    <%= f.label "参加人数", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.text_field :number, class:"input-short" %>
    <span>人</span>
    </div>
  </div>

  <div class="field">
    <%= f.label "参加費(一人あたり)", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.text_field :cost, class:"input-short" %>
    <span>円</span>
    </div>
  </div>

  <div class="field-long">
    <%= f.label "イベント内容", class:"item" %>
    <div class="mandatory">必須</div>
    <div class="input">
    <%= f.text_area :text, class:"input-long" %>
    </div>
  </div>

  <%# <input name="event[user_id]" type="hidden" value=<%= current_user.id%>

  <div class="submit">
    <%= f.submit "作 成  ＞" ,class:"button-submit"%> 
  </div>


<% end %>

</div>

app/views/events/show.html.erb
<div class='event-show'>

<div class='event-show-top'>

    <div class='show-side'>
      <div class='show-user'>
        <%= link_to image_tag(@event.user.image, class: "show-user-img"), "/users/#{@event.user.id}" %>
        <%= link_to @event.user.nickname, "/users/#{@event.user.id}", class:'show-user-name'%>
      </div>

      <ul class='show-item'>

        <li class='show-date'>
          <div class="material-icons s">date_range</div>
          <span class='show-date-day'>
            <%= @event.day.year %>年
            <%= @event.day.month %>月
            <%= @event.day.day %>日
            <% day = @event.day.wday %>
            <% days = ["(日)", "(月)", "(火)", "(水)", "(木)", "(金)", "(土)"] %>
            <% if days[day] == "(日)"%>
              <span class='mon'><%= days[day] %></span>
            <% elsif days[day] == "(土)"%>
              <span class='sat'><%= days[day] %></span>
            <% else %>
              <%= days[day] %>
            <% end %>
          </span>
        </li>

        <li class='show-time'>
          <div class="material-icons s">access_time</div>
          <%= @event.start_time.hour %>時
          <%= @event.start_time.min %>分〜
          <%= @event.end_time.hour %>時
          <%= @event.end_time.min %>分
        </li>

        <li class='show-level'>
          <div class="material-icons s">sports_tennis</div>
          <span class='lv'>参加Lv.</span>
            <% if @event.levelev[:name] == "初級"%>
              <div class='level-2'><%= @event.levelev[:name] %></div>
            <% elsif @event.levelev[:name] == "初中級"%>
              <div class='level-3'><%= @event.levelev[:name] %></div>
            <% elsif @event.levelev[:name] == "中級"%>
              <div class='level-4'><%= @event.levelev[:name] %></div>
            <% elsif @event.levelev[:name] == "中上級"%>
              <div class='level-5'><%= @event.levelev[:name] %></div>
            <% elsif @event.levelev[:name] == "上級"%>
              <div class='level-6'><%= @event.levelev[:name] %></div>
            <% elsif @event.levelev[:name] == "どなたでも"%>
              <div class='level-7'><%= @event.levelev[:name] %></div>
            <% end %>
        </li>

        <% unless @event.limit == nil %>
        <li class='show-number'>
          <div class="material-icons s">pan_tool</div>
          制限：<%= @event.limit %>
        </li>
        <% end %>

        <li class='show-place'>
          <%= link_to @event.place_url do %>
            <div class="material-icons sp">room</div>
          <% end %>
          <%= @event.place %>
        </li>

        <li class='show-number'>
          <div class="material-icons s">groups</div>
          プレー人数：<%= @event.number %>人
        </li>

        <li class='show-cost'>
          <div class="material-icons s">payments</div>
          <%= @event.cost %>円(一人あたり)
        </li>

      </ul>

    </div>

    <div class='show-main'>
      <div class='show-title'><%= @event.title %></div>
      <div class='show-text'><%= @event.text %></div>
    </div>

</div>

  <% if user_signed_in? %>
    <%= form_with(model: [@event, @event_user], local: true) do |f| %>
      <%= f.text_field :text, class:"input-participation", placeholder:"例）〇〇です。よろしくお願いします。" %>
      <div class="show-submit">
        <%= f.submit "メッセージを送信して イベントに参加する ＞", class:"show-button-submit" %> 
      </div>
    <% end %>
  <% end %>

</div>

  <div class="participant-back">

    <div class="participant">
     <div class='participant-text'>現在の参加者</div>

      <div class="participant-users">
          <% @events.each do |event| %>
            <div class='participant-user'>
              <%= link_to image_tag(event.user.image, class: "participant-user-img"), "/users/#{event.user.id}" %>
              <div class='participant-user-name'>
                <%= link_to event.user.nickname, "/users/#{event.user.id}",class:"participant-user-name-text" %>
              </div>
            </div>
          <% end %>
      </div>
   </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trint</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body class="is-slide" id="page-animate">
    <%= render "shared/header" %>
      <%= yield %>
    <%= render "shared/footer" %>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class='footer-left'>
    <%= image_tag "logo_01.svg" , class:"logo-01" %>
    <p> © 2020 TRINT</p>
  </div>

  <ul class='footer-right'>
    <li><%= link_to "サービス概要", "/" , class:"footer-text" %></li>
    <li><%= link_to "よくある質問", "/" , class:"footer-text" %></li>
    <li><%= link_to "お問い合わせ", "/" , class:"footer-text" %></li>
  </ul>

</footer>

app/views/shared/_header.html.erb
<header>

  <%= link_to image_tag("logo_01.svg", class:"logo-01"), "/" %>

  <div class='header-right'>

  <ul class='header-list'>
    <li><%= link_to "イベントを作成する", new_event_path , class:"header-text" %></li>
    <li><%= link_to "イベントを探す", events_path, class:"header-text" %></li>
  </ul>

  <% if user_signed_in? %>
    <div class='button'>
      <%= link_to current_user.nickname, "/users/#{current_user.id}", class:"my" %>
      <%= link_to "Log out ▶︎", destroy_user_session_path, method: :delete, class:"logout" %>
    </div>
  <% else %>
    <div class='button'>
      <%= link_to "Sign in ▶︎", new_user_session_url , class:"login" %>
      <%= link_to "NEW ▶︎", new_user_registration_url , class:"new" %>
    </div>
  <% end %>

</div>

</header>

app/views/top/index.html.erb
<div class='main'>

<%# コンテンツ01 %>

  <div class='contents-01' >

<%# <%= video_tag("/videos/pixta_42848784.mp4", autoplay: :true, loop: :true, muted: :true, size:"1200x700", class: 'video-content') %>

    <div class='top-01-01'>
      <%= image_tag "top_01_01.svg" %>
    </div>
    <div class='top-01-02'>
      <%= image_tag "top_01_02.svg"%>
    </div> 
  </div>

<%# コンテンツ02 %>
  
  <div class='contents-02'>

  <div class='top-02-01'>
    <%= image_tag "top_02_icon.svg" %>
  </div>

   <div class="top-02-02">
    <div class="info">
      <div class="info-01">
          <div class="day">2020.12.11</div>
          <div class="text">リニューアルしました。新機能をお試しください！</div>
      </div>
      <%= link_to "more", "/" , class:"more" %>
    </div>
  </div>

   <div class="top-02-02">
    <div class="info">
      <div class="info-01">
          <div class="day">2020.12.11</div>
          <div class="text">リニューアルしました。新機能をお試しください！</div>
      </div>
      <%= link_to "more", "/" , class:"more" %>
    </div>
  </div>

   <div class="top-02-02">
    <div class="info">
      <div class="info-01">
          <div class="day">2020.12.11</div>
          <div class="text">リニューアルしました。新機能をお試しください！</div>
      </div>
      <%= link_to "more", "/" , class:"more" %>
    </div>
  </div>


  </div>

  </div>

<%# コンテンツ03 %>

  <div class='contents-03'>

    <div class='top-03'>
      <div class='top-03-top'>
        <%= image_tag "top_03_line.svg", class:'top-03-line'%>
        <%= image_tag "top_03_01.svg", class:'top-03-01'%>
      </div>
        <%= image_tag "top_03_03.jpg", class:'top-03-03' %>
    </div>

    <div class='top-03-02'>
      <%= image_tag "top_03_02.svg" %>
    </div>

  </div>


<%# コンテンツ04 %>

  <div class='contents-04'>

    <div class='top-04-main'>
      <%= image_tag "top_04_01.jpg", class:'top-04-01'%>
      <div class='top-04-main-box'>
      <p class='top-04-main-text'>
      TRINTは誰もが気軽に<br>
      テニスを楽しむためのアプリです<br>
      いろんなイベントを通して<br>
      仲間を増やしたり技術を高めたり<br>
      もっとテニスライフを楽しみましょう！<br>
      </p>
      <%= link_to "イ ベ ン ト を 探 す ＞", events_path, class:"top-04-main-btn" %>
      </div>
    </div>

    <div class='top-04-box'></div>

    <div class='top-04-sub'>
        <%= image_tag "top_04_02.jpg", class:'top-04-02' %>
        <%= image_tag "top_04_03.jpg", class:'top-04-02' %>
        <%= image_tag "top_04_04.jpg", class:'top-04-02' %>
        <%= image_tag "top_04_05.jpg", class:'top-04-02' %>
    </div>

    <div class='top-04-box'></div>


</div>

app/views/users/show.html.erb
<div class='user-show'>

  <div class='user-show-items'>

    <div class='show-user-face'>
      <%= image_tag @user.image, class: "show-user-img s"  %>
      <div class='show-user-name s'><%= @user.nickname %></div>
    </div>

    <div class='show-user-item'>
      <ul class='user-items'>
        <li class='user-item'><%= @user.age[:name] %></li>
        <li class='user-item'><%= @user.sex[:name] %></li>
        <li class='user-item'>
              <% if @user.level[:name] == "初級"%>
                <div class='level-2'><%= @user.level[:name] %></div>
              <% elsif @user.level[:name] == "初中級"%>
                <div class='level-3'><%= @user.level[:name] %></div>
              <% elsif @user.level[:name] == "中級"%>
                <div class='level-4'><%= @user.level[:name] %></div>
              <% elsif @user.level[:name] == "中上級"%>
                <div class='level-5'><%= @user.level[:name] %></div>
              <% elsif @user.level[:name] == "上級"%>
                <div class='level-6'><%= @user.level[:name] %></div>
              <% elsif @user.level[:name] == "どなたでも"%>
                <div class='level-7'><%= @user.level[:name] %></div><% end %>
        </li>
        <li class='user-item'>テニス歴<%= @user.history %>年</li>
      </ul>
      <div class='user-text'>
        <div class='user-profile'><%= @user.profile %></div>
      </div>
    </div>
    
  </div>


  <div class="Organizer-back">

  <div class='Organizer-text'>主催イベント</div>

    <ul class='event-lists-item'>
      <li class='status-item'>状況</li>
      <li class='date-time-item'>日程</li>
      <li class='event-contents-item'>内容</li>
      <li class='organizer-item'>主催者</li>
    </ul>

    <div class='event-lists'>
      <% @events.each do |event| %>
        <ul class='event-list'>
          <div class='status-box'>
          <li class='status'>募集中</li>
          </div>

          <li class='date-time'>
            <span class='date'>
            <%= event.day.year %>年<br>
            <%= event.day.month %>月
            <%= event.day.day %>日
            <% day = event.day.wday %>
            <% days = ["(日)", "(月)", "(火)", "(水)", "(木)", "(金)", "(土)"] %>
            <% if days[day] == "(日)"%>
              <span class='mon'><%= days[day] %></span>
            <% elsif days[day] == "(土)"%>
              <span class='sat'><%= days[day] %></span>
            <% else %>
              <%= days[day] %>
            <% end %>
          </span>
          </li>
        
          <li class='event-contents'>
            <% if event.levelev[:name] == "初級"%>
              <div class='level-2'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "初中級"%>
              <div class='level-3'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "中級"%>
              <div class='level-4'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "中上級"%>
              <div class='level-5'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "上級"%>
              <div class='level-6'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "どなたでも"%>
              <div class='level-7'><%= event.levelev[:name] %></div>
            <% end %>
            <%= link_to event_path(event.id),class:"contents-title" do %>
              <%= event.title %>
            <% end %>
          </li>

          <li class='organizer'>
          <div class='user-img'>
            <%= image_tag event.user.image, class: "user-img" %></div>
          <div class='user-name'><%= event.user.nickname %></div>
          </li>

        </ul>
      <% end %>
    </div>
  </div>


  <div class="participation-back">

  <div class='participation-text'>参加中イベント</div>

    <ul class='event-lists-item'>
      <li class='status-item'>状況</li>
      <li class='date-time-item'>日程</li>
      <li class='event-contents-item'>内容</li>
      <li class='organizer-item'>主催者</li>
    </ul>

    <div class='event-lists'>
      <% @events.each do |event| %>
      <%# <% @events.include?(@event_users) do%> 
        <ul class='event-list'>
          <div class='status-box'>
          <li class='status'>募集中</li>
          </div>

          <li class='date-time'>
            <span class='date'>
            <%= event.day.year %>年<br>
            <%= event.day.month %>月
            <%= event.day.day %>日
            <% day = event.day.wday %>
            <% days = ["(日)", "(月)", "(火)", "(水)", "(木)", "(金)", "(土)"] %>
            <% if days[day] == "(日)"%>
              <span class='mon'><%= days[day] %></span>
            <% elsif days[day] == "(土)"%>
              <span class='sat'><%= days[day] %></span>
            <% else %>
              <%= days[day] %>
            <% end %>
          </span>
          </li>
        
          <li class='event-contents'>
            <% if event.levelev[:name] == "初級"%>
              <div class='level-2'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "初中級"%>
              <div class='level-3'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "中級"%>
              <div class='level-4'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "中上級"%>
              <div class='level-5'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "上級"%>
              <div class='level-6'><%= event.levelev[:name] %></div>
            <% elsif event.levelev[:name] == "どなたでも"%>
              <div class='level-7'><%= event.levelev[:name] %></div>
            <% end %>
            <%= link_to event_path(event.id),class:"contents-title" do %>
              <%= event.title %>
            <% end %>
          </li>

          <li class='organizer'>
          <div class='user-img'>
            <%= image_tag event.user.image, class: "user-img" %></div>
          <div class='user-name'><%= event.user.nickname %></div>
          </li>

        </ul>

      <% end %>
    </div>
    
  </div>

</div>